name: Allow step fail

on: [workflow_dispatch]

jobs:
  this-will-error:
    runs-on: ubuntu-latest
    steps:
      - name: This will Error
        run: exit 1
        continue-on-error: true
      - uses: actions/checkout@v4
      - uses: ./.github/actions/composite