name: Access context, and env

on: [workflow_dispatch]

jobs:
  see-env:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REPOSITORY
        name: (ENV) GitHub Repository
      - run: echo $GITHUB_ACTOR
        name: (ENV) GitHub Actor
      - run: echo $GITHUB_REF
        name: (ENV) GitHub REF
      - run: echo $GITHUB_REF_NAME
        name: (ENV) GitHub REF NAME
