name: Deployment Protection

on: [push]

jobs:
  thing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello thing"
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: echo "Hello deploy"
    
