name: Calling reusable workflow

on: [workflow_dispatch]

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'calling after this'
  call-custom:
    uses: ./.github/workflows/use-custom-action.yml
  