name: Step Output

on:
  workflow_dispatch:

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PET=DOG" >> $GITHUB_OUTPUT
  use-output:
    runs-on: ubuntu-latest
    needs: [print]
    steps:
      - run: echo "accessing output ${{ steps.print.outputs.PET }}"
  