name: Trigger manually

on:
  workflow_dispatch:
    inputs:
      text:
        description: text itself
        type: string
        required: true

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print it
        run: |
          echo Hello, ${{ github.event.inputs.text }}
        
