name: Use default working-directory

on: [workflow_dispatch]

defaults:
  run:
    shell: bash
    working-directory: './scripts'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          chmod +x run.sh
          ./run.sh
